Update legislation.tex
clearhaus/cake-legislation pull request #9
Opened 2022-09-26 10:25 UTC by mep-clearhaus

New and up-to-date version of the cake legislation.

OBS, I need someone to be create a PDF version of this whenever merged.

New stuff
- Added both Quickpay and 3DSecure.io, and their employees, as potential COR. 
- Removed item relating to Dinero
- Added "Size"/"Amount" in relation *Cake*
- Adding a rule relating to the POP2 Padel Court
- Removing superfluous paragraphs to ensure we are being served a little less cake than the old legislation was permitting

2022-09-26 10:34 UTC, ct-clearhaus submitted a review, later dismissed
Nice! 🎾

Should we add also 🏓 while we're at it? 🤔

2022-09-26 10:34 UTC, ct-clearhaus commented on legislation.tex
> +  \item This legislation applies to all employees of Clearhaus, Quickpay, and 3DSecure.io.
```suggestion
  \item This legislation applies to all employees of Clearhaus, Quickpay, and 3dsecure.io.
```

Capitalisation cf. https://datacvr.virk.dk/enhed/virksomhed/41019328.

2022-09-26 10:34 UTC, ct-clearhaus commented on legislation.tex
> +  \item Going from student position, internship or similar non-full-time-employment to Full-time employment in Clearhaus, Quickpay, or 3DSecure.io.
```suggestion
  \item Going from student position, internship or similar non-full-time-employment to Full-time employment in Clearhaus, Quickpay, or 3dsecure.io.
```

Consequence.

2022-09-26 10:45 UTC, mep-clearhaus commented
> Should we add also 🏓 while we're at it? 🤔

Yes!

2022-09-26 17:53 UTC, cbobach commented
We were considering if we should add that `Clearhaus gives cake if network is down` 🤷🏻

2022-09-27 19:18 UTC, brorbw commented
Something like `If wifi down > 15 min CH will provide cake`. This will also make up for missed cake due to removal of sections

2022-09-27 20:41 UTC, Lassejoe commented
> wifi down > 15 min

Or `if Wi-Fi down multiple times same day`
Or `if Wi-Fi down due to new settings`

2022-09-28 07:56 UTC, mep-clearhaus commented
I've tried to add the wifi disturbance input :D Please check it out

2022-09-28 08:33 UTC, cbobach reviewed
Suggestion 🤷🏻

2022-09-28 08:33 UTC, cbobach commented on legislation.tex
> +  \item If wifi down > 15 min, or/and wifi down > 2 times on one day (calendar days, not 24 hours) POP2 will provide cake
```suggestion
  \item If network down > 15 min, or/and network down > 2 times on one day (calendar days, not 24 hours) POP2 will provide cake
```

2022-09-28 11:18 UTC, kbadk commented on legislation.tex
>    \item Occupying a meeting room booked by another person (without leaving immediately)
```suggestion
  \item Occupying a meeting room booked by another person (without leaving immediately).
```

2022-09-28 11:19 UTC, kbadk commented on legislation.tex
> +  \item If network down > 15 min, or/and network down > 2 times on one day (calendar days, not 24 hours) POP2 will provide cake
```suggestion
  \item If network down > 15 min, and/or network down > 2 times on one day (calendar days, not 24 hours) POP2 will provide cake.
```

2022-09-28 15:50 UTC, brorbw requested changes

2022-09-28 15:50 UTC, brorbw commented on legislation.tex
> +  \item If network down > 15 min, and/or network down > 2 times on one day (calendar days, not 24 hours) POP2 will provide cake.
`or` should suffice. Its ambiguous if both conditions should apply /s
```suggestion
  \item If network down > 15 min, or network down > 2 times on one day (calendar days, not 24 hours) POP2 will provide cake.
```

2022-09-29 19:05 UTC, brorbw approved these changes

2022-09-30 10:52 UTC, merged